version: '3.9'

services:
  zamleaks:
    build: .
    restart: unless-stopped
    container_name: zamleaks
    # network_mode: bridge
    # command: /bin/sh -c "python3 /var/globaleaks/globaleaks.py"
    # command: /bin/sh -c "/usr/bin/python3 /usr/bin/globaleaks --working-path=/var/globaleaks/ -n"
    # volumes:
      # - zamleaks:/var/globaleaks
      # - 'tor:/var/lib/tor'
    ports:
      - 80:8080
      - 443:8443

volumes:
  zamleaks: {}
    # driver: local
  tor: {}
    # driver: local
