contact_links:
  - name: Ask the community on the Community Forum
    url: https://zamleaks.com
    about: Ask and discuss questions with other community members on the Community Forum.

  - name: Chat with the community on the Community Chat
    url: https://community.zamleaks.com
    about: Chat with the other community members on the Community Chat.
