version: '3'

services:
  zamleaks:
    build: .
    restart: unless-stopped
    container_name: zamleaks
    network_mode: bridge
    volumes:
      - zamleaks:/var/globaleaks
    ports:
      - 80:8080
      - 443:8443

volumes:
  zamleaks:
